CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    role VARCHAR(30) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    tags VARCHAR(2000),
    constraints VARCHAR(3000),
    description VARCHAR(5000),
    examples VARCHAR(5000),
    solution_explanation VARCHAR(5000),
    starter_code VARCHAR(5000),
    category VARCHAR(255),
    difficulty VARCHAR(255) CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE,
    problem_id BIGINT NOT NULL REFERENCES problem(id),
    user_id BIGINT REFERENCES app_user(id),
    correctness VARCHAR(3000),
    feedback_summary VARCHAR(3000),
    bugs VARCHAR(5000),
    edge_cases VARCHAR(5000),
    hint VARCHAR(5000),
    suggested_improvement VARCHAR(5000),
    ai_feedback VARCHAR(10000),
    submitted_code VARCHAR(10000) NOT NULL,
    language VARCHAR(255),
    space_complexity VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('PENDING', 'REVIEWED', 'FAILED')),
    time_complexity VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS test_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hidden BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    problem_id BIGINT NOT NULL REFERENCES problem(id),
    expected_output VARCHAR(3000),
    input VARCHAR(3000)
);

CREATE TABLE IF NOT EXISTS mock_interview_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_minutes INTEGER NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    problem_id BIGINT NOT NULL REFERENCES problem(id),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    status VARCHAR(30) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED'))
);

CREATE INDEX IF NOT EXISTS idx_problem_difficulty ON problem(difficulty);
CREATE INDEX IF NOT EXISTS idx_problem_category ON problem(category);
CREATE INDEX IF NOT EXISTS idx_submission_problem_id ON submission(problem_id);
CREATE INDEX IF NOT EXISTS idx_submission_user_id ON submission(user_id);
CREATE INDEX IF NOT EXISTS idx_submission_status ON submission(status);
CREATE INDEX IF NOT EXISTS idx_submission_created_at ON submission(created_at);
CREATE INDEX IF NOT EXISTS idx_test_case_problem_id ON test_case(problem_id);
CREATE INDEX IF NOT EXISTS idx_mock_interview_user_started ON mock_interview_session(user_id, started_at DESC);
